Repository typehero/typehero, pull requests merged in 2023-11, with the labels that each got.

#1125 feat: aot feature flag
  apps/web/src/utils/feature-flags.ts
Labels: enhancement, advent of typescript

#1128 feat: stub out aot 2023
  apps/admin/src/components/navigation.tsx
  apps/web/src/app/[locale]/aot-2023/_components/card-grid.tsx
  apps/web/src/app/[locale]/aot-2023/_components/challenge-card.tsx
  apps/web/src/app/[locale]/aot-2023/_components/index.tsx
  apps/web/src/app/[locale]/aot-2023/page.tsx
  apps/web/src/components/Navigation/index.tsx
  apps/web/src/locales/en.ts
  challenges/aot/2023/blank/metadata.json
  challenges/aot/2023/blank/prompt.md
  challenges/aot/2023/blank/solutions/1.ts
  challenges/aot/2023/blank/tests.ts
  challenges/aot/2023/blank/tsconfig.json
  challenges/aot/2023/blank/user.ts
Labels: advent of typescript

#1126 feat: aot: seed local track
  packages/db/seed/data/tracks.ts
Labels: enhancement, advent of typescript

#1138 feat: aot badges
  apps/web/src/app/[locale]/(profile)/[username]/_components/badges/aot-2023-badge.tsx
  apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/_actions.ts
  apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/badges.tsx
  apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/index.tsx
  apps/web/src/app/[locale]/(profile)/[username]/_components/profile.tsx
  packages/ui/src/icons.ts
Labels: enhancement, advent of typescript

#1200 fix: aot landing on mobile
  apps/web/src/app/[locale]/aot-2023/_components/about.tsx
  apps/web/src/app/[locale]/aot-2023/_components/index.tsx
Labels: fix

#1202 feat: add rewards+badges section under "About" aot
  apps/web/src/app/[locale]/aot-2023/_components/about.tsx
Labels: enhancement

#1211 fix: fix aot bronze badge
  apps/web/src/app/[locale]/(profile)/[username]/_components/dashboard/_actions.ts
Labels: fix
