Repository typehero/typehero, pull requests merged in 2023-10, with the labels that each got.

#820 feat: adds beta token for early access
  apps/web/package.json
  apps/web/src/app/[locale]/(playgrounds)/challenge-playground/page.tsx
  apps/web/src/app/[locale]/challenge/[id]/getChallengeRouteData.ts
  apps/web/src/app/[locale]/challenge/[id]/page.tsx
  apps/web/src/app/[locale]/challenge/[id]/solutions/[solutionId]/page.tsx
  apps/web/src/app/[locale]/challenge/[id]/submissions/[[...catchAll]]/page.tsx
  apps/web/src/app/[locale]/claim/_actions.ts
  apps/web/src/app/[locale]/claim/_schema.ts
  apps/web/src/app/[locale]/claim/claim-form.tsx
  apps/web/src/app/[locale]/claim/page.tsx
  apps/web/src/app/[locale]/explore/_components/index.tsx
  apps/web/src/app/[locale]/login/_components/LoginButton.tsx
  apps/web/src/app/[locale]/login/page.tsx
  apps/web/src/app/[locale]/tracks/[slug]/page.tsx
  apps/web/src/app/[locale]/tracks/_components/index.tsx
  apps/web/src/app/[locale]/wizard/page.tsx
  apps/web/src/app/feature-flag-provider.tsx
  apps/web/src/components/carousel.tsx
  apps/web/src/components/navigation.tsx
  apps/web/src/middleware.ts
  apps/web/src/utils/feature-flags.ts
  apps/web/src/utils/server/is-beta-user.ts
  packages/auth/src/server.ts
  packages/db/mocks/user.mock.ts
  packages/db/schema.prisma
  packages/db/temp/export-tokens.ts
  packages/db/temp/populate-tokens.ts
  pnpm-lock.yaml
Labels: ＳＫＩＬＬ　ＩＳＳＵＥ

#806 feat: add in-challenge track overview
  apps/web/src/app/[locale]/challenge/[id]/submissions/[[...catchAll]]/save-submission.action.ts
  apps/web/src/app/[locale]/challenge/[slug]/comments/[commentId]/page.tsx
  apps/web/src/app/[locale]/challenge/[slug]/getChallengeRouteData.ts
  apps/web/src/app/[locale]/challenge/[slug]/layout.tsx
  apps/web/src/app/[locale]/challenge/[slug]/left-wrapper.tsx
  apps/web/src/app/[locale]/challenge/[slug]/page.tsx
  apps/web/src/app/[locale]/challenge/[slug]/solutions/page.tsx
  apps/web/src/app/[locale]/challenge/[slug]/submissions/[[...catchAll]]/save-submission.action.ts
  apps/web/src/app/[locale]/challenge/[slug]/wrapper.tsx
  apps/web/src/app/[locale]/challenge/_components/challenge-layout-wrapper.tsx
  apps/web/src/app/[locale]/challenge/_components/challenge-track-navigation.tsx
  apps/web/src/app/[locale]/challenge/_components/challenge-track-outline.tsx
  apps/web/src/app/[locale]/challenge/_components/description/index.tsx
  apps/web/src/app/[locale]/tracks/_components/track-challenge-card.tsx
  apps/web/src/utils/feature-flags.ts
  packages/db/schema.prisma
  packages/ui/package.json
  packages/ui/src/components/sheet.tsx
Labels: enhancement

#882 feat: fit-and-finish profile page for early access
  apps/web/src/app/[locale]/[username]/_components/dashboard/bookmarks-tab.tsx
  apps/web/src/app/[locale]/[username]/_components/dashboard/in-progress-tab.tsx
  apps/web/src/app/[locale]/[username]/_components/dashboard/index.tsx
  apps/web/src/app/[locale]/[username]/_components/dashboard/overview-tab.tsx
  apps/web/src/app/[locale]/[username]/_components/dashboard/overview.tsx
  apps/web/src/app/[locale]/[username]/_components/dashboard/shared-solutions-tab.tsx
  apps/web/src/app/[locale]/[username]/_components/dashboard/submissions-tab.tsx
  apps/web/src/app/[locale]/[username]/_components/profile.tsx
  packages/db/schema.prisma
Labels: enhancement

#883 💫 pre-compiled real-time ray-tracing with linear-gradients
  apps/og-image/app/components/logo3d.tsx
  apps/web/src/app/[locale]/_components/hero.tsx
  apps/web/src/components/navigation.tsx
  apps/web/src/styles/globals.css
Labels: hacktoberfest

#881 contributors grid redesign, fixes #837
  apps/web/src/app/[locale]/_components/community/community.tsx
  apps/web/src/app/[locale]/_components/community/contributor.tsx
  apps/web/src/styles/globals.css
Labels: hacktoberfest

#921 fix: profile bio width
  apps/web/src/app/[locale]/[username]/_components/dashboard/overview-tab.tsx
Labels: fix

#956 Support for Documentation Added
  docs/procedures/000-run-e2e-tests.md
Labels: documentation
